# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'tarea6' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for tarea6
	pod 'dogsImage', :git => 'https://github.com/aleal04/dogImage.git'

end
