# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'cenfotec-gram' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SDWebImageSwiftUI'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Firestore'
  pod 'URLImage'
  
end
